### ISSUE TITLE
"NOT FOUND" Page after CTR Transfer

### ISSUE THREAD

**Issue by Thogan2** [SomeoneWeird/aergia#2]
I have tried to run AERGIA on two PC's now, and everything goes great up until after the CTR Transfer Setup page.  The CTR downloads and extracts and I reach the page with the large check mark saying Success!, but when I click next I reach a page that simply says NOT FOUND and contains no information and has no button to move on to the next page.  There is a button to go back and it takes me back the CTR page, but nothing seems to work for me getting past this step.  I have not yet put the SD card back into the 3DS, instead I reformat then place it into the 3DS remove it and start over.  Have I missed a step?  Or is there an issue with my dependancies?  Below I pasted some errors that showed up in my command prompt window after the NOT found page appeared:

```
`WARNING in ./~/colors/lib/colors.js
Critical dependencies:
127:29-43 the request of a dependency is an expression
 @ ./~/colors/lib/colors.js 127:29-43

WARNING in ./~/colors/lib/extendStringPrototype.js
Critical dependencies:
106:31-45 the request of a dependency is an expression
 @ ./~/colors/lib/extendStringPrototype.js 106:31-45

WARNING in ./~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in C:\.......\Desktop\aergia-master\node_modules\ws\lib
 @ ./~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in C:\........\Desktop\aergia-master\node_modules\ws\lib
 @ ./~/ws/lib/Validation.js 10:19-44
webpack: bundle is now VALID.`

```

Any ideas what I might be able to do to fix this?  Thanks.

**Comment by SomeoneWeird** [comment]
There's still a long way to go until this is ready to be used - the WIP section in the readme doesn't really convey that yet, I'll fix it.

If you want to install CFW please follow the guide at https://3ds.guide
